version: 33
jobs:
  - name: Go Tests
    steps:
      - !CheckoutStep
        name: Checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: Test
        runInContainer: true
        image: golang
        interpreter: !DefaultInterpreter
          commands: |
            go test -v
        useTTY: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: Vet
        runInContainer: true
        image: golang
        interpreter: !DefaultInterpreter
          commands: |
            go vet
        useTTY: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !PullRequestUpdateTrigger {}
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 3600
  - name: Build Docker Image
    steps:
      - !CheckoutStep
        name: Checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !BuildImageWithKanikoStep
        name: Build Image
        output: !RegistryOutput
          destinations: git.justlab.xyz/alertflow/runner/alertflow_runner:@branch@ git.justlab.xyz/alertflow/runner/alertflow_runner:latest
        builtInRegistryAccessTokenSecret: push_secret
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !PullRequestMergeTrigger
        branches: develop main
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 3600
