---

LogLevel: info
RunnerID: 1bed8e52-3cb3-4ade-b2db-71e6b070f619
Mode: master

Alertflow:
  URL: http://localhost:8080
  APIKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoiNjkzYWIzMTAtODczYi00YzU2LThjMGYtMzNhMzM5ZDZhYTc4IiwiaWQiOiJkMGRiNzJlMi02YThjLTQwNWItYTQwYi00ZjEzMjA2ZWJjMDAiLCJ0eXBlIjoicnVubmVyIiwiZXhwIjozMzA2NTAwMzgwfQ.ZYK4nMLMlKYsfvQS6tFKIa-B3DQNZsDUXe4wRvqbHpg

Payloads:
  Enabled: true
  Port: 8081
  Managers:
    - Alertmanager
