---

LogLevel: info
RunnerID: fc367864-c7ed-4193-9916-cce5357c4069
Mode: worker

Alertflow:
  URL: http://localhost:8080
  APIKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoiZjhmNzg1YmUtMjg3ZS00YTkxLWFhMTItOTJiNjI1OWJmN2YzIiwiaWQiOiIzNTdkYzhhOS03OTUzLTQ5MmUtOWQxMC0wNjAyNzliNzMzNzUiLCJ0eXBlIjoicnVubmVyIiwiZXhwIjozMzA1ODcwNjYyfQ.9TFb3qBSz_Rd4FpTwd8on6yVFJZQkqkDJkMKwtaspYE

Payloads:
  Enabled: true
  Port: 8081
  Managers:
    - Alertmanager
