---

LogLevel: info
RunnerID: ffa1a024-5e8f-4b91-b3d3-b0b7a9d94363
Mode: master

Alertflow:
  URL: http://localhost:8080
  APIKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoiYzBmMjkyNmQtMWM0MS00MWQxLWJjM2UtMjI2YzJiM2ZlOTUzIiwiaWQiOiI3NTg0ZmE4OS04NTcyLTRhNGYtYjA3My0xMGFhMTc4NzI3MmEiLCJ0eXBlIjoicnVubmVyIiwiZXhwIjozMzA1MDAzNzM4fQ.Q3dCXAyHwm98y79juRze1iIuv0Xaa-S-QzSbRgq6xcM

Payloads:
  Enabled: true
  Port: 8081
  Managers:
    - Alertmanager
