---

logLevel: info
mode: master

alertflow:
  url: https://alertflow.org
  runner_id: null
  api_key: null

plugins:
  - name: log
    repository: https://github.com/AlertFlow/rp-alertmanager
    version: v1.0.2

payload_endpoints:
  port: 8081
