---

logLevel: info
mode: master

alertflow:
  url: https://alertflow.org
  runnerID: null
  apiKey: null

plugins:
  - name: log
    url: gitlab.justlab.xyz/alertflow-public/runner-plugins/log
    version: v1.0.2

payload_endpoints:
  port: 8081
