---

LogLevel: info
RunnerID: null
Mode: master

Alertflow:
  URL: https://alertflow.org
  APIKey: null

Plugins:
  - name: log
    url: gitlab.justlab.xyz/alertflow-public/runner-plugins/log

PayloadEndpoints:
  Port: 8081
