name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Runner Docker Image
        run: docker build . --file Dockerfile --tag justnz/alertflow-runner:latest --tag justnz/alertflow-runner:${{ github.sha }} --tag justnz/alertflow-runner:${{ github.ref_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          docker push justnz/alertflow-runner:latest
          docker push justnz/alertflow-runner:${{ github.sha }}
          docker push justnz/alertflow-runner:${{ github.ref_name }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Protoc Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate Protobuf
        run: |
          protoc --go_out=internal/plugin --go_opt=paths=source_relative \
            --go-grpc_out=internal/plugin --go-grpc_opt=paths=source_relative \
            proto/plugin.proto

      - name: Build
        run: go build -v ./...

      - name: Build Release Binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -o bin/alertflow-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o bin/alertflow-darwin-arm64
          GOOS=linux GOARCH=amd64 go build -o bin/alertflow-linux-amd64

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          artifacts: 'bin/*'
          skipIfReleaseExists: true
          generateReleaseNotes: true
          token: ${{ secrets.ACCESS_TOKEN }}
